version: "3.9"
services:
  app:
    container_name: api
    build: .
    volumes:
      - ./:/app
    command: "nodemon -L server.js"
    ports: 
      - 5000:5000
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql